apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./pvc/pvc-sigstore-pipeline-storage.yaml
  - ./task-cleanup.yaml
  - ./task/task-image-sign-and-push.yaml
  - ./task/upload-signature.yaml
  - image-sign-and-push-pipeline.yaml

